Repository jlandersen/vscode-kafka, pull requests merged in 2021-04, with the labels that each got.

#155 Update fakerjs to 5.5.2
  package-lock.json
  package.json
Labels: dependencies

#160 Customize cluster context with provider id
  package.json
  src/explorer/models/cluster.ts
Labels: enhancement

#163 Fix comment snippet
  CHANGELOG.md
  snippets/producers.json
Labels: bug, completion

#165 Add 'Discover Cluster Providers' command
  CHANGELOG.md
  docs/Explorer.md
  docs/assets/kafka-explorer-discover-providers.png
  package.json
  src/extension.ts
Labels: enhancement

#175 Show cluster state in kafka file
  CHANGELOG.md
  src/client/client.ts
  src/client/index.ts
  src/explorer/models/cluster.ts
  src/extension.ts
  src/kafka-file/kafkaFileClient.ts
  src/kafka-file/languageservice/kafkaFileLanguageService.ts
  src/kafka-file/languageservice/services/codeLensProvider.ts
Labels: clusters, kafka-file

#176 Hide internal strimzi topics/consumers by default
  CHANGELOG.md
  package.json
Labels: enhancement
